### ISSUE TITLE
Return more than the REST body in emitted message

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/rest-api-component#102]
Currently, the REST API component sets the HTTP body to the emitted message body. This has the following problems:
* When the response is not a JSON object, pass-through breaks
* There is no way to use headers or response code information later in the flow
* The option `dontThrowErrorFlg` causes the struture of the response to change along with behavior in the flow.

An approach that we can borrow from the OpenAPI Component is to assign the emitted message body three properties:
* `headers` - corresponding to the HTTP headers received in the response 
* `body` - corresponding to the HTTP body received in the response
* `responseCode` - corresponding to the HTTP status code received in the response.

This option is not backwards compatible either than the proposed option, but it may be more beneficial.

_Originally posted by @jhorbulyk in https://github.com/elasticio/rest-api-component/issues/88#issuecomment-581300674_

**Comment by zubairov** [comment]
@jhorbulyk setting `header` and `responseCode` should not break the backwards compatibility, is it correct?

**Comment by jhorbulyk** [comment]
> setting `header` and `responseCode` should not break the backwards compatibility, is it correct?

Currenlty, the REST response body becomes the body of the message emitted by the component. The problem with this approach is that there is no natural place to set `header` and `responseCode` thus requiring a backwards incompatible change.
