### ISSUE TITLE
Credentials verification of OAuth2 credentials should check validity of refresh_token

### ISSUE THREAD

**Issue by zubairov** [elasticio/rest-api-component#114]
When validating OAuth2 credentials we should make sure the `refresh_token` is available and can be still used for fetching the `access_token`. 
P.S. Don't forget to update the keys in the DB after verification, sometimes new `refresh_token` can be given back together with "new" `access_token`

**Comment by ShkarupaNick** [comment]
as I know, we do not have an opportunity to emit keys from verify credentials execution context

**Comment by jhorbulyk** [comment]
> as I know, we do not have an opportunity to emit keys from verify credentials execution context

Correct.  See https://github.com/elasticio/sailor-nodejs/issues/57

**Comment by mhaidar** [comment]
This has broken my REST API components using OAuth2. They were working fine and they were refreshing the tokens. The error I constantly get is `No refresh tokens were returned by the OAuth2 provider. Try to add access_type:offline as an additional parameter`
I tried the additional parameter. No Luck
I had to downgrade back to version 2.

**Comment by kirill-levitskiy** [comment]
> This has broken my REST API components using OAuth2. They were working fine and they were refreshing the tokens. The error I constantly get is `No refresh tokens were returned by the OAuth2 provider. Try to add access_type:offline as an additional parameter`
> I tried the additional parameter. No Luck
> I had to downgrade my component to the previous version.

@mhaidar could you check and share the commit of the affected component's version, please?

**Comment by luzhok** [comment]
the problem is really reproducible on all our stages (sparrow, westeros) with the last version of REST-API component. But maybe, the problem isn't with the component, but after implementing https://app.zenhub.com/workspaces/elasticio-59cb79abd6a2a75883931c56/issues/elasticio/elasticio/3440 ????

**Comment by mhaidar** [comment]
@kirill-levitskiy the affected component version is f3e0f2d0f39ea1c7465d584fff04fcc0a8cf6d1c
The functioning component version is 91b35d105f8bfe215159b565b05fc877fe102593

The commit that caused this is from this issue 114
22242e227f7802274fc0a56a8ae612786166d0a8

Basically that validation message I never used to get.
Are you expecting a new refresh token on every request?

**Comment by kirill-levitskiy** [comment]
@mhaidar thanks for your report. We executed tests and confirmed the bug.

**Comment by luzhok** [comment]
we've created a bug for investigation in our repo: https://github.com/elasticio/elasticio/issues/3707

**Comment by shulkaolka** [comment]
> This has broken my REST API components using OAuth2. They were working fine and they were refreshing the tokens. The error I constantly get is No refresh tokens were returned by the OAuth2 provider. Try to add access_type:offline as an additional parameter

@mhaidar could you check one more time with the new version of the component? It is possibly fixed.

**Comment by mhaidar** [comment]
@shulkaolka working thanks
