### ISSUE TITLE
Use Secrets Management Service for OAuth in the REST API component

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/rest-api-component#136]
Recentlly, our platform team has added functionality to the platform so that it is now possible to synchronize secrets between running containers under the label [**Secrets Management Service for OAuth**](https://docs.elastic.io/releases/2020-06-04.html#secrets-management-service-for-oauth). We should use this feature in this component.

The end result should be that if container A and container B are running at the same time, and container A recieves updated credentials currently, those credentials will be available container B while it is running.

## To replicate
1. Create two flows, each of which use the REST API component with the same OAuth credential.
1. Set the flows to realtime and start both flows.
1. Use the https://api.integration.squiz.cloud/v2/credentials API to PATCH this credential with an expired date.

Expected result should be that both flow obtain new valid OAuth credentials.

**Comment by shulkaolka** [comment]
Example for implementation https://github.com/elasticio/secrets-reference-component

**Comment by jhorbulyk** [comment]
Blocked by https://github.com/elasticio/elasticio/issues/4253 and https://github.com/elasticio/elasticio/issues/4255

**Comment by A3a3e1** [comment]
https://github.com/elasticio/rest-api-component/pull/139
