### ISSUE TITLE
REST Client should encode body parameters for x-www-form-encoded

### ISSUE THREAD

**Issue by zubairov** [elasticio/rest-api-component#141]
Currently when using following configuration with HTTP Post:

![image](https://user-images.githubusercontent.com/56208/87826626-84a18f80-c879-11ea-9051-b5f215b4c0cc.png)

the value of body parameter `data` should be URLEncoded, however that does not happen.

**Comment by jhorbulyk** [comment]
@zubairov Can I ask you to provide:
* Steps to reproduce
* Expected Result
* Actual Result
?

**Comment by zubairov** [comment]
Steps to reproduce - send a HTTP Request with HTTP Component using configuration on the picture
Expected Result - data is encoded
Actual Result - data is not encoded
