### ISSUE TITLE
Add support of ";,/?:@&=+$" in URI params

### ISSUE THREAD

**Issue by umkaline** [elasticio/rest-api-component#146]
The last released changed has broken support of the following characters in URI parameters ";,/?:@&=+$"
https://github.com/elasticio/rest-api-component/pull/144

As they are not encoded with encodeURI (that was used), they need to be encoded manually with encodeURIComponent.
As a result, they would be encoded to %xx state.
But, encodeURI will encode % again into %xx.

As a result at this point, there is no possibility to use characters ";,/?:@&=+$" in the URI.

A typical use-case is when an integrator tries to use an email with a "+" sign.

**Comment by andrewreshitko** [comment]
The component is deprecated.
The task is not relevant anymore.
