### ISSUE TITLE
Proposal: Make URL base part of the credentials

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/rest-api-component#148]
Originally proposed in https://github.com/elasticio/rest-api-component/issues/49

## Suggestion
Add a new field to the credentials object: **Base URL** that would be a text input.  When making REST calls, the component would append (potentially with `/` deduplication) the value of the URL provided in the incoming message.

E.g. Company has test.somesystem.theirurl.com for testing and prod.somesystem.theirurl.com and they want to build their flows with their test system first before changing them to point at their prod system some point in the future.

An alternative is to use input from the config component but this option might be better.

**Comment by andrewreshitko** [comment]
The component is deprecated.
The task is not relevant anymore.
