### ISSUE TITLE
Header fields have a squeezed JSONata field

### ISSUE THREAD

**Issue by drobiazko** [elasticio/rest-api-component#23]
![elastic io popeye 2017-10-02 20-17-18](https://user-images.githubusercontent.com/464220/31092496-e9499624-a7ae-11e7-833b-4de9a9667c0f.png)

**Comment by jhorbulyk** [comment]
I'm not sure if this item is still relevant with the new mapper. Things no longer feel too condensed.
![Screenshot from 2020-09-21 14-27-36](https://user-images.githubusercontent.com/5710732/93766372-9ce5b000-fc16-11ea-9c42-aacc905ee5bf.png)
