### ISSUE TITLE
New Authentication strategy - query parameter

### ISSUE THREAD

**Issue by zubairov** [elasticio/rest-api-component#49]
Right now we have following authentication methods in REST Client component:

![image](https://user-images.githubusercontent.com/56208/37043451-ee405a7e-2160-11e8-8c9c-4b855368eaa5.png)

However some APIs, like [Pipedrive](https://developers.pipedrive.com/docs/api/v1/?#/) for example require users to add an API Key to **each** HTTP request as parameter (in this example `api_key`) 

![image](https://user-images.githubusercontent.com/56208/37043521-1b4bd570-2161-11e8-8da3-403d89ffa1eb.png)

This is a stupid decision but frequently used by inexperienced PHP developers.

## Suggestion

Add a new authentication method - `Query parameter` that work similar to `HTTP Header` but just transparently adds a query parameter to each query. Advantage - centralized management of credentials despite the stupid API design.

**Comment by jhorbulyk** [comment]
Closing in favor of https://github.com/elasticio/elasticio/issues/4350
