### ISSUE TITLE
Add an option to override default handling of Content-Type

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/rest-api-component#59]
Add an option to REST Client to override default handling of `Content-Type`, with following options

- Default - Use the Content-Type of the response and the existing rules in the component.
- Parse as JSON - Try to parse a payload as JSON regardless of content type reported. Throw an error if the response is not valid JSON.
- Parse as XML - Try to parse a payload as XML and automatically transform it to JSON later using conventional rules. Throw an error if the response is not valid XML.
- Treat Response as Text - Don't perform any XML/JSON/etc parsing on the response body. Instead, treat the body like a text string and emit that in the message. To avoid the bug with non-object JSON we likely will have to emit data of the form: `{value: <textRespresentationOfResponseBody>}`
- Store as attachment - Regardless of Content-Type, create an attachment in stewart and store the entire contents of the body in that attachment.  Ideally, no transformation (e.g. character encoding application) of the data shoud be performed.  In the outbound message, the attachment should include the url fetched and the data from the HTTP headers.

**Comment by andrewreshitko** [comment]
The component is deprecated.
The task is not relevant anymore.
