### ISSUE TITLE
Migration of rest-api-component to REST client library

### ISSUE THREAD

**Issue by A3a3e1** [elasticio/rest-api-component#69]
The task should be done when the `component-commons` library will be built
https://github.com/elasticio/projects/issues/192

**Comment by ShkarupaNick** [comment]
Last Investigation result
![Rest-api-component.png](https://images.zenhubusercontent.com/5b5ef5637227d91973c4ce99/bd9005ba-1d35-4fe1-a19a-d5543ed0eb92)

**Comment by shulkaolka** [comment]
Blue blocks with functions are supposed to be implemented in [commons-library] (https://github.com/elasticio/component-commons-library)

**Comment by ShkarupaNick** [comment]
I can suggest split this task into 2 parts.

Firstly, we should improve the commons library for supporting all features of the rest API component.
Estimation with these improvements - 21 sp.

The second one - refactoring of Rest-API-component - 21 sp.

**Comment by andrewreshitko** [comment]
The component is deprecated.
The task is not relevant anymore.
