### ISSUE TITLE
Consider migrating away from xml2js library

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/rest-api-component#70]
## Description

In many places in our ecosystem, we use `xml2js` to convert from XML to JSON (e.g. when procesing incoming webhook requests with XML data).  However, [the memory consumption of this library isn't good](https://github.com/elasticio/odata2openapi/issues/36) and [migrating to a different library with the same behavoir might be beneficial](https://github.com/elasticio/odata2openapi/pull/37)

## Definition of Done

No code explicitly references the library `xml2js`.

**Comment by jhorbulyk** [comment]
Potentially blocked by nashwaan/xml-js#141

**Comment by andrewreshitko** [comment]
The component is deprecated.
The task is not relevant anymore.
