### ISSUE TITLE
Component should automatically encode the request URL

### ISSUE THREAD

**Issue by zubairov** [elasticio/rest-api-component#79]
In case following configuration of REST API Component:

![image](https://user-images.githubusercontent.com/56208/62219716-1a18ea80-b3af-11e9-9674-e54a3cb16846.png)

and `company_name` contain non-english characters, e.g. `成都探码科技有限公` the error will be generated:

![image](https://user-images.githubusercontent.com/56208/62219796-3ddc3080-b3af-11e9-9076-797848319f58.png)

This error can be avoided if we could encode the not allowed characters in URL.

**Comment by juhrmacher** [comment]
I will reopen the issue, because it looks like the implemented behavior does not meet all requirements

**Comment by stas-fomenko** [comment]
closed by mistake

**Comment by andrewreshitko** [comment]
The component is deprecated.
The task is not relevant anymore.
