### ISSUE TITLE
Add the ability to transform results once received

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/rest-api-component#91]
*Implements the functionality described in https://github.com/elasticio/elasticio/issues/2793 at a component level (assuming that it is not implemented at a platform level).*

*Continuation of https://github.com/elasticio/rest-api-component/issues/68 where the transform logic is added.*

Currently, the REST API component has an option where the results of the API call can be spilt assuming the body is an array.  However, many times the result is not a naked array in the body but a large array wraped in a JSON object with a single property.  (e.g. `{"results": [...big array...]}`)  In order to handle this case, we should consider adding an input box for a JSONata expression to transform the body of the step once it is produced. (Should default to the idempotent JSONata expression $)  This transformation should be applied prior to splitting (if selected).

**Comment by andrewreshitko** [comment]
The component is deprecated.
The task is not relevant anymore.
