### ISSUE TITLE
Component should be able to handle attachment information via the message body

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/rest-api-component#95]

**Comment by A3a3e1** [comment]
@jhorbulyk Could you pls provide more description/acceptance criteria?

**Comment by shulkaolka** [comment]
My suggestion is to create a branch from https://github.com/elasticio/rest-api-component/pull/139 and release these two task together

**Comment by jhorbulyk** [comment]
## Acceptance Criteria
When the REST API component produces an attachment, the following metainformation for the produces attachment should be in the outgoing message.body:
* `url`: Stewart (or similar) URL
* `size`: Size in bytes of the attachment
* `content-type`: Content type associated with the attachment
* `sourceUrl`: URL where the attachment was originally fetched from.
